# Generated by Django 5.1 on 2024-08-15 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=1000, null=True)),
                ('payment_method_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('http', models.CharField(max_length=255)),
                ('https', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('datewanted', models.DateField()),
                ('timewanted', models.TimeField()),
                ('hoursba', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('reservation', models.CharField(max_length=255)),
                ('rundate', models.DateField()),
                ('runtime', models.TimeField()),
                ('runnow', models.BooleanField()),
                ('nonstop', models.BooleanField()),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('retry', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('minidle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('maxidle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('account', models.ForeignKey(db_column='account_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='botui.account')),
                ('proxy', models.ForeignKey(db_column='proxy_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='botui.proxy')),
            ],
        ),
    ]
