# Generated by Django 5.1 on 2024-08-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='api_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
