# Generated by Django 5.1 on 2024-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0003_alter_account_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
