# Generated by Django 5.1 on 2024-08-20 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0004_account_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('datewanted', models.DateField()),
                ('timewanted', models.TimeField()),
                ('hoursba', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('reservation', models.CharField(max_length=255)),
                ('rundate', models.DateField()),
                ('runtime', models.TimeField()),
                ('runnow', models.BooleanField()),
                ('nonstop', models.BooleanField()),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('retry', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('minidle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('maxidle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('proxy_name', models.CharField(max_length=255)),
                ('proxy_http', models.CharField(max_length=255)),
                ('proxy_https', models.CharField(max_length=255)),
                ('reservation_name', models.CharField(max_length=255)),
                ('account_email', models.EmailField(max_length=254)),
                ('account_password', models.CharField(max_length=255)),
                ('account_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('account_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('account_payment_method_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='pid',
        ),
    ]
