# Generated by Django 5.1 on 2024-08-20 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0005_botrun_remove_account_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommand',
            name='reservation',
            field=models.ForeignKey(db_column='reservation_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='botui.reservationtype'),
        ),
    ]
