# Generated by Django 5.1 on 2024-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0006_alter_botcommand_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='proxy',
            name='http',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='https',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
