# Generated by Django 5.1 on 2024-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0007_alter_reservationtype_options_alter_proxy_http_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
