# Generated by Django 5.1 on 2024-08-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0010_alter_botcommand_duration_alter_botrun_account_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botrun',
            name='reservation',
        ),
    ]
