# Generated by Django 5.1 on 2024-09-06 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botui', '0012_botrun_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCheckRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('timewanted', models.TimeField()),
                ('hoursba', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('nonstop', models.BooleanField()),
                ('minidle', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(600)])),
                ('maxidle', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(600)])),
                ('retrysec', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(9.99)])),
                ('multiproxy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('multiproxy_value', models.CharField(blank=True, max_length=255, null=True)),
                ('reservation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_email', models.CharField(blank=True, max_length=255, null=True)),
                ('account_password', models.CharField(blank=True, max_length=255, null=True)),
                ('account_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('account_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('account_payment_method_id', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multiproxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BotCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('timewanted', models.TimeField()),
                ('hoursba', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('nonstop', models.BooleanField()),
                ('minidle', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(600)])),
                ('maxidle', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(600)])),
                ('retrysec', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(9.99)])),
                ('account', models.ForeignKey(db_column='account_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='botui.account')),
                ('reservation', models.ForeignKey(db_column='reservation_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='botui.reservationtype')),
                ('multiproxy', models.ForeignKey(db_column='multiproxy_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='botui.multiproxy')),
            ],
        ),
    ]
